### ISSUE TITLE
Disqus comment plugin doesn't show up

### ISSUE THREAD

**Issue by huozhi** [yyypasserby/yyypasserby.github.io#2]
I read your new post, but I didn't see the disqus comment input box.
There was no error showing up in debug console. Did you remove the disqus plugin in your blog? :)

**Comment by yyypasserby** [comment]
It's not an error, disqus has been disabled. For I can't find the former blog comments when I changed from jekyll to pelican. I feel sad, so I disable it.

**Comment by huozhi** [comment]
Well, that's OK. I have migrated all comments once time. Maybe you just made wrong configs. We could talk about this issue at other dinners.
